# Generated by Django 5.0.4 on 2024-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('bodeguero', 'Bodeguero'), ('contador', 'Contador'), ('default', 'Default')], default='default', max_length=20),
        ),
    ]
